export const languages = {
	javascript: {
		label: "JavaScript",
		value: "javascript",
		sample: `console.log("Hello World");`,
		extension: ".js",
		mime: "text/javascript",
	},
	typescript: {
		label: "TypeScript",
		value: "typescript",
		sample: `console.log("Hello World");`,
		extension: ".ts",
		mime: "text/typescript",
	},
	python: {
		label: "Python",
		value: "python",
		sample: `print("Hello World")`,
		extension: ".py",
		mime: "text/python",
	},
	java: {
		label: "Java",
		value: "java",
		sample: `public class HelloWorld {\n\tpublic static void main(String[] args) {\n\t\tSystem.out.println("Hello World");\n\t}\n}`,
		extension: ".java",
		mime: "text/java",
	},
	csharp: {
		label: "C#",
		value: "csharp",
		sample: `Console.WriteLine("Hello World");`,
		extension: ".cs",
		mime: "text/csharp",
	},
	php: {
		label: "PHP",
		value: "php",
		sample: `echo "Hello World";`,
		extension: ".php",
		mime: "text/php",
	},
	sql: {
		label: "SQL",
		value: "sql",
		sample: `SELECT * FROM users;`,
		extension: ".sql",
		mime: "text/sql",
	},
	go: {
		label: "Go",
		value: "go",
		sample: `import "fmt"\nfunc main() {\n\tfmt.Println("Hello World")\n}`,
		extension: ".go",
		mime: "text/go",
	},
	rust: {
		label: "Rust",
		value: "rust",
		sample: `println!("Hello World");`,
		extension: ".rs",
		mime: "text/rust",
	},
	cpp: {
		label: "C++",
		value: "cpp",
		sample: `#include <iostream> \nusing namespace std;\nint main() {\n\tcout << "Hello, Monaco Editor!" << endl;\n\treturn 0;\n}`,
		extension: ".cpp",
		mime: "text/cpp",
	},
	c: {
		label: "C",
		value: "c",
		sample: `#include <stdio.h>\nint main() {\n\tprintf("Hello, Monaco Editor!");\n\treturn 0;\n}`,
		extension: ".c",
		mime: "text/c",
	},
};
