name: Create Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Type check
        run: bun run type-check

      - name: Build Chrome extension
        run: bun run build:chrome

      - name: Build Firefox extension
        run: bun run build:firefox

      - name: Get version from package.json
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
            echo "tag_name=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "version=$(cat package.json | jq -r .version)" >> $GITHUB_OUTPUT
            echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      - name: Create extension packages
        run: |
          # Create Chrome package
          cd dist/chrome
          zip -r ../../xodeforces-${{ steps.version.outputs.version }}-chrome.zip .
          cd ../..
          
          # Create Firefox package
          cd dist/firefox
          zip -r ../../xodeforces-${{ steps.version.outputs.version }}-firefox.zip .
          cd ../..

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.tag_name }}
          name: Release ${{ steps.version.outputs.tag_name }}
          files: |
            xodeforces-${{ steps.version.outputs.version }}-chrome.zip
            xodeforces-${{ steps.version.outputs.version }}-firefox.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Chrome artifact
        uses: actions/upload-artifact@v4
        with:
          name: xodeforces-chrome-${{ steps.version.outputs.version }}
          path: xodeforces-${{ steps.version.outputs.version }}-chrome.zip

      - name: Upload Firefox artifact
        uses: actions/upload-artifact@v4
        with:
          name: xodeforces-firefox-${{ steps.version.outputs.version }}
          path: xodeforces-${{ steps.version.outputs.version }}-firefox.zip
